#!/usr/bin/python3

import os
import sys, cgi


print("Content-type: text/html\r\n")

print("<HTML>")
print("<BODY>")

print("<P><hr><p>")

print("Server", os.environ.get('SERVER_NAME'))

print("<P><hr><p>")

for param in os.environ.keys():
    print("<b>%20s</b>: %s<br>" % (param, os.environ[param]))

print("<P><hr><p>")

form = cgi.FieldStorage()
data = form.getvalue('name')
print(data)

print("<P><hr><p>")

print("</BODY>")
print("</HTML>")
